const UPDATE_PROFILE="user:UPDATE_PROFILE"
const UPDATE_PASSWORD="user:UPDATE_PASSWORD"
const REPORT_USER="user:REPORT_USER"
const BLOCK_USER_BY_ADMIN="admin:BLOCK_USER_BY_ADMIN"
const DEACTIVATE="user:DEACTIVATE"

module.exports={
    UPDATE_PROFILE,
    UPDATE_PASSWORD,
    REPORT_USER,
    BLOCK_USER_BY_ADMIN,
    DEACTIVATE
}